mambu-tap enhancements
singer-io/tap-mambu pull request #44
Opened 2021-05-21 13:31 UTC by DownstreamDataTeam

# Description of change
(write a short description or paste a link to JIRA)
1. Endpoint used for extracting loan accounts is changed from GET to POST /search
2. Endpoint used for extracting deposit accounts is changed from GET to POST /deposits:search
3. A new field is added for the Installments table for parent account key  
4. A new table is added to the tap, for Audit trail [schema]
5. Define the endpoint configuration for the Audit Trail schema and implement logic for the new endpoint 

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-05-21 13:31 UTC, cmerrick commented
Hi @DownstreamDataTeam, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

2021-05-25 20:09 UTC, cosimon requested changes

2021-05-26 09:14 UTC, DownstreamDataTeam commented
We made the requested changed: added exception on self.__apikey_audit + removed .idea folder and log_state_stream.json and log_per_api.json.zip + removed all changes to the pull_request_template

2021-08-20 15:36 UTC, zachharris1 commented
Merged in via #49

2021-08-20 15:36 UTC, closed without merging