Multithreading improvement
singer-io/tap-mambu pull request #84
Opened 2022-07-06 11:42 UTC by DownstreamDataTeam

# Description of change
- Implemented multithreading by:
  -  offset: as before
  -  bookmark: new method, reducing maximum offset to improve performance by moving through the stream using filters instead of offset
  - bookmark: same as above, but instead of using date time, it uses date as filters
- Child streams are extracted using multithreading.
- Added unit tests for the multithreading implementation.
- Changed `page_size` default value from `500` to `200`
- Hardcoded the `page_size` and `max_threads` for some streams in order to improve performance and avoid causing extreme loads
- Removed the multithreading POC file
- Some streams are not using multithreading because of technical issues.
 
# Rollback steps
 - revert this branch

2022-08-02 19:03 UTC, dmosorast requested changes
Some changes requested and comments. I think the biggest blocker here is the usage of `set` for deduping (for performance and consistency reasons).

2022-08-04 11:37 UTC, DownstreamDataTeam commented on tap_mambu/tap_generators/multithreaded_bookmark_generator.py
> +        for offset in [offset for offset in range(0, self.batch_limit, self.artificial_limit)]:
Yes, you are correct, I don't know how this got here

2022-08-04 11:51 UTC, DownstreamDataTeam commented on tap_mambu/tap_generators/multithreaded_bookmark_generator.py
> +            temp_buffer = set([json.dumps(record, ensure_ascii=False).encode("utf8") for record in transformed_batch])
I'll have to look into this, as it's the only way we could reliably test if records are continuous (as the order between batches is not consistent... which is why we used sets)

What you said about ordering of keys not being guaranteed is true, but from our testing it seems to hold up. I'll try tackling this for a bit and see if I can come up with anything better.

2022-08-04 12:02 UTC, DownstreamDataTeam commented on tap_mambu/tap_generators/multithreaded_offset_generator.py
> +            LOGGER.warning("Error checking returned errors, but they will be corrected!")
Changed

2022-08-04 12:02 UTC, DownstreamDataTeam commented on tap_mambu/tap_generators/multithreaded_offset_generator.py
> +            LOGGER.info("Cleanup complete! Retrying extraction from last bookmark...")
Changed

2022-08-04 12:02 UTC, DownstreamDataTeam commented on setup.py
> +          'pytz==2018.4'
Somehow had an older version locally and assumed it's the latest. Changed to 2022.1

2022-08-04 12:03 UTC, DownstreamDataTeam commented on tap_mambu/tap_generators/multithreaded_bookmark_generator.py
> +        # in order to paginate through the data using date, resetting offset to 0
I've reformulated this comment to describe what we actually mean

2022-08-04 12:04 UTC, DownstreamDataTeam commented on tap_mambu/helpers/multithreaded_requests.py
> +    _dispatcher = ThreadPoolExecutor(max_workers=100)
This could be an idea, yes. Maybe we should talk more about this once I finish up fixing stuff after this review

2022-08-10 18:12 UTC, dmosorast requested changes
Just a few more changes for performance requested, we can talk about this more in depth if you'd like.

2022-08-11 05:45 UTC, DownstreamDataTeam commented on tap_mambu/helpers/hashable_dict.py
> +            return self.__key() == other.__key()
Sorry, I'm not sure what you mean by equality being a required property of __hash__.
Also, it feels like changing equality from key to hash(key) could result in collisions for records that are not the same but result in the same hash.

2022-08-11 05:51 UTC, DownstreamDataTeam commented on tap_mambu/helpers/hashable_dict.py
> +        return json.dumps(sorted(data, key=lambda record: record[0]))
You're right, for some reason I did not think about using tuples instead of strings. Thanks, I'll replace all json.dumps with tuple conversions

2022-08-11 17:27 UTC, dmosorast commented on tap_mambu/helpers/hashable_dict.py
> +            return self.__key() == other.__key()
That's my mistake. I misread the statement in that Python documentation (and it seems like I need to review my Data Structures textbook 😅). At first read I interpreted this to also mean that hashes that are equal map to objects that are equal.
> The only required property is that objects which compare equal have the same hash value

2022-08-12 14:04 UTC, dmosorast commented on tap_mambu/tap_generators/multithreaded_offset_generator.py
>              LOGGER.exception("Discrepancies found in extracted data, and errors couldn't be corrected."
Discussed in Slack, this can be included in the next PR.

2022-08-12 14:04 UTC, dmosorast approved these changes

2022-08-12 14:09 UTC, merged